name: Build and Tests

on:  
  push:
    #branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
        - '**.cs'
        - '**.csproj'

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Restore Packages
        run: nuget restore Wuerfelspiel.sln

      - name: Build Solution
        run: |
          msbuild.exe Wuerfelspiel.sln /p:platform="Any CPU" /p:configuration="Release"

      - name: show Folder
        run: |
          cd WuerfelspielTests\obj\Release\
          dir
        shell: cmd
        
      - name: Run Tests
        run: vstest.console.exe .\WuerfelspielTests\obj\Release\WuerfelspielTests.dll #/FailWhenNoTestsFound:true
